# Generated by Django 3.0.4 on 2020-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletext',
            name='rotate',
            field=models.BooleanField(default=True, verbose_name='Обратное изображение'),
        ),
    ]
